apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=EksP@$s
resources:
  - create-rbac.yaml
  - create-efs-provisioner.yaml
  - create-storage.yaml
  - mysql-deployment.yaml
  - wordpress-deployment.yaml